import { Link } from "wouter";
import { ArrowLeft } from "lucide-react";

export function TermsPage() {
  const year = new Date().getFullYear();

  return (
    <div className="min-h-screen w-full overflow-y-auto bg-gradient-to-b from-background to-muted/30">
      <div className="max-w-3xl mx-auto px-6 py-10">
        <Link href="/">
          <span className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors cursor-pointer mb-6">
            <ArrowLeft className="w-4 h-4" /> Back to app
          </span>
        </Link>

        <h1 className="text-3xl font-bold tracking-tight">Terms &amp; Conditions</h1>
        <p className="mt-2 text-sm text-muted-foreground">
          © {year} MadeTVProducts. All rights reserved. Last updated {new Date().toLocaleDateString()}.
        </p>

        <div className="mt-8 space-y-8 text-sm leading-relaxed text-foreground/90">
          <section>
            <h2 className="text-lg font-semibold mb-2">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Made Super AI Agent (the "Service"), a product of MadeTVProducts,
              you agree to be bound by these Terms &amp; Conditions. If you do not agree, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">2. Ownership &amp; Copyright</h2>
            <p>
              The Service, including its software, design, branding, text, graphics, and all related
              materials, is owned by MadeTVProducts and protected by copyright, trademark, and other
              intellectual property laws. © {year} MadeTVProducts. All rights reserved. You may not copy,
              reproduce, distribute, modify, or create derivative works from any part of the Service
              without prior written permission from MadeTVProducts.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">3. Use of the Service</h2>
            <p>
              You agree to use the Service lawfully and responsibly. You are responsible for any content
              you create, generate, or download using the Service, including apps, videos, and other output.
              You retain ownership of content you create, while MadeTVProducts retains all rights to the
              underlying platform and tools.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">4. User Control &amp; AI Conduct</h2>
            <p>
              You have full control over the AI at all times. The AI is designed to assist you and will
              never attempt to override, take over, or alter your computer, accounts, or systems without
              your explicit consent. The AI acts only within this application and provides guidance for any
              actions performed outside it.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">5. AI-Generated Content</h2>
            <p>
              Output produced by the Service is generated by artificial intelligence and is provided "as is."
              While we strive for high quality, MadeTVProducts does not guarantee the accuracy, completeness,
              or fitness of any generated content for a particular purpose. Review all output before relying on it.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">6. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, MadeTVProducts shall not be liable for any indirect,
              incidental, or consequential damages arising from your use of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">7. Changes to These Terms</h2>
            <p>
              MadeTVProducts may update these Terms &amp; Conditions from time to time. Continued use of the
              Service after changes constitutes acceptance of the revised terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">8. Contact</h2>
            <p>
              For questions about these Terms &amp; Conditions, please contact MadeTVProducts.
            </p>
          </section>
        </div>

        <p className="mt-12 text-center text-xs text-muted-foreground">
          © {year} MadeTVProducts. All rights reserved.
        </p>
      </div>
    </div>
  );
}
